### ISSUE TITLE
Using with getServerSideProps

### ISSUE THREAD

**Issue by joshkopecek** [antonybudianto/react-ua#9]
## When using getServerSideProps throws "You can not use getInitialProps with getServerSideProps"

I recently switched a few pages to `getServerSideProps`, but only one has `withUserAgent`. I'd like to use `getServerSideProps` on all of them, but it's currently impossible with this setup.

## To Reproduce

1. Switch to `getServerSideProps`
1. Wrap with `withUserAgent`
1. Try to render a page

## Expected behavior

It should detect if you're using `getServerSideProps`

**Comment by antonybudianto** [comment]
v3.0.0 is just released with new React hooks, so you don't need to wrap with HOC anymore.
I've plan to deprecate and remove HOC api in the future, in favor of React hooks.
